### ISSUE TITLE
Inference test seems to ingest floating point numbers

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/DynODE#162]
The `tests/test_inferer.py` test seems to take in a floating point number array that then gets past to `Dist.Poisson` inside of `numpyro.sample` e.g. 

https://github.com/cdcent/cfa-scenarios-model/blob/dfbd4ded9fddf2dafcd793f73f751e6067ccd9f2/tests/test_inferer.py#L46-L49

I don't think this is really testing inference, but rather the fail mode of numpyro?

**Comment by arik-shurygin** [comment]
closing this issue as we moved to int rounding in the tests regardless:
https://github.com/CDCgov/DynODE/blob/a58c2d123b29113b0b8d443fdfb0f93fb8e3ce71/tests/test_inferer.py#L52C1-L52C62
