### ISSUE TITLE
Sanitize poetry, modules, etc.

### ISSUE THREAD

**Issue by edbaskerville** [CDCgov/DynODE#263]
This issue is written vaguely for now, because my current understanding of the issue is quite vague.

There seem to be some problems related to the way poetry configuration, modules, Python search path, etc. are organized.

We should do a review of what's going on, see what needs to be done to make it make sense, and reorganize accordingly.

Will record more concrete thoughts below as they emerge.

@arik-shurygin

**Comment by SamuelBrand1** [comment]
I am here for guinea pig purposes if you need a typical user model specimen.

**Comment by arik-shurygin** [comment]
Closed by #293 as we are now a single package in this repo!
