### ISSUE TITLE
Wrap Azure setup/launch in command-line-runnable scripts

### ISSUE THREAD

**Issue by edbaskerville** [CDCgov/DynODE#264]
Right now, if you try to run [src/mechanistic_azure/experiment_setup.py](https://github.com/cdcent/cfa-scenarios-model/blob/main/src/mechanistic_azure/experiment_setup.py) or [src/mechanistic_azure/experiment_launcher_azure.py](https://github.com/cdcent/cfa-scenarios-model/blob/main/src/mechanistic_azure/experiment_launcher_azure.py) from the command line, you get a module error.

It would be nice to be able to run these directly as command-line executables, without any interaction with Python.

Proposal:

1. Move the code that executes when running these files into `run()` functions of the module with function arguments corresponding to command-line arguments.
2. Wrap these `run()` functions in new files, `scripts/set_up_azure_experiment.py` and `scripts/launch_azure_experiment.py` that handle command-line argument parsing and ensure the correct Python module path is used.

These may also be affected by #263.

**Comment by arik-shurygin** [comment]
I like this idea, to add onto it we may want something like `scripts/set_up_local_env.py` which can download raw data and fill in the `data/` folder as needed by #272

**Comment by arik-shurygin** [comment]
Closing this issue due to creation of [scenarios-hpc-azure](https://github.com/[CDCgov/scenarios-hpc-azure](https://github.com/CDCgov/scenarios-hpc-azure)) to fill this role
